OnlineShop/Cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', CartDetail.as_view(), name='cart'),
    path('add/<int:product_id>/', CartAdd.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemove.as_view(), name='cart_remove'),
    path('add_quanity/<int:product_id>/', CartAddQuantity.as_view(), name='cart_add_quantity'),
    path('minus_quantity/<int:product_id>/', CartMinusQuantity.as_view(), name='cart_minus_quantity')
]

OnlineShop/OnlineShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('online-shop/', include('HomePage.urls')),
    path('online-shop/cart/', include('Cart.urls')),
    path('online-shop/products/', include('Products.urls')),
    path('online-shop/orders/', include('Order.urls')),
#    path('paypal/', include('paypal.standard.ipn.urls')),
    path('online-shop/payment/', include('Payment.urls')),
    path('online-shop/customer/', include('Users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineShop/Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    path('registration/', Registration.as_view(), name='registration'),
    path('authentication/', Authentication.as_view(), name='authentication'),
    path('logout/', Logout.as_view(), name='logout'),
    path('account/', UserDetailPage.as_view(), name='customer-account'),
    path('password-reset/', UserResetPassword.as_view(), name='password-reset'),
    path('reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name='Users/password-reset-confirmation.html'),
         name='confirmation'),
    path('password-reset/complete/',
         views.PasswordResetDoneView.as_view(template_name='Users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', UserChangePassword.as_view(), name='password-change'),
    path('settings/change-email/', UserChangeEmailView.as_view(), name='change-email'),
    path('my-orders/', UserOrders.as_view(), name='user-orders'),
    path('order-detail/<int:order_id>/', UserOrderDetail.as_view(), name='user-order-detail'),
    path('my-coupons/', UserCoupons.as_view(), name='user-coupons')
]

OnlineShop/Order/models.py
from django.contrib.auth import get_user_model
from django.db import models
from Products.models import Product
from .services import *
from Products.services import get_price_sep
from Products.services import get_price_in_usd
from Coupons.models import Coupons

User = get_user_model()


class Order(models.Model):
    """Model of orders"""

    ORDER_STATUSES = (
        (1, 'Completed'),
        (2, 'In progress')
    )
    name = models.CharField(max_length=300, verbose_name="Name")
    last_name = models.CharField(max_length=300, verbose_name='Last name')
    surname = models.CharField(max_length=300, verbose_name='Surname', blank=True)
    phone = models.CharField(max_length=200, verbose_name='Phone number', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Order creation date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Order update date')
    email = models.EmailField(verbose_name='Email', blank=True)
    address = models.CharField(max_length=250, verbose_name='Address')
    post_office = models.CharField(max_length=200, verbose_name='Post office', blank=True)
    country = models.CharField(max_length=250, verbose_name='Country', blank=True)
    city = models.CharField(max_length=250, verbose_name='City or town', blank=True)
    paid = models.BooleanField(default=False, verbose_name='Paid')
    order_total_price = models.IntegerField(verbose_name='Order total price', default=0)
    order_total_price_usd = models.IntegerField(verbose_name='Order total price in USD', default=0)
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             verbose_name='User',
                             null=True,
                             blank=True)
    use_bonuses = models.BooleanField(verbose_name='Use bonuses?', default=False)
    order_status = models.IntegerField(verbose_name='Order status', default=2, choices=ORDER_STATUSES)
    order_bonuses = models.IntegerField(default=0, verbose_name='Order bonuses')
    order_bonuses_usd = models.IntegerField(default=0, verbose_name='Order bonuses in usd')
    coupon = models.ForeignKey(Coupons,
                               on_delete=models.SET_NULL,
                               verbose_name='Coupon',
                               blank=True,
                               null=True)

    def __str__(self):
        return f"Order ID: {self.id}, customer name and last name: {self.name} {self.last_name}"

    class Meta:
        verbose_name = 'order'
        verbose_name_plural = 'Orders'

    def get_order_total_price_view(self):
        """
        Method for getting order total price
        in normal string representation.
        More about it in 'Products.services.py'
        """

        order_total_price_view = get_price_sep(self.order_total_price)
        return order_total_price_view

    def get_order_total_price_usd_view(self):
        order_total_price_usd_view = get_price_sep(self.order_total_price_usd)
        return order_total_price_usd_view


class OrderItem(models.Model):
    """Model of orders items"""

    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Order')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Product')
    price = models.IntegerField(verbose_name='Product price')
    price_usd = models.IntegerField(verbose_name='Price per item in dollars', default=0)
    quantity = models.PositiveIntegerField(default=1, verbose_name='Quantity of product')
    item_total_price = models.IntegerField(verbose_name='Total price of item', default=0)
    item_total_price_usd = models.IntegerField(verbose_name='Total price of item in usd', default=0)

    def __str__(self):
        return f'ID: {self.id}'

    def save(self, *args, **kwargs):
        """
        Calculating total price and total price in
        USD currency of item.
        """

        self.item_total_price = get_product_cost(self.price, self.quantity)
        self.item_total_price_usd = get_price_in_usd(self.item_total_price)
        return super(OrderItem, self).save(*args, **kwargs)

    def get_total_price_view(self):
        item_total_price_view = get_price_sep(self.item_total_price)
        return item_total_price_view

    def get_total_price_usd_view(self):
        item_total_price_usd_view = get_price_sep(self.item_total_price_usd)
        return item_total_price_usd_view

OnlineShop/Users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserRegistration(UserCreationForm):
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'autocomplete': 'email'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'autocomplete': 'password'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'autocomplete': 'password'}))

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserAuthentication(AuthenticationForm):
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'autocomplete': 'email'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'autocomplete': 'password'}))


class UserResetPasswordForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your email'}))


class UserChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password',
                                   widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label='New password',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label='New password confirmation',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label='New email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        users = User.objects.all()
        emails_list = []

        for user in users:
            emails_list.append(user.email)

        if email in emails_list:
            self.add_error("email", "This email is already taken!")
        return email

OnlineShop/Users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import View
from django.contrib import messages
from django.views.generic import ListView

from Coupons.models import Coupons
from .forms import UserRegistration, AuthenticationForm, UserResetPasswordForm, UserChangePasswordForm, ChangeEmailForm
from django.contrib.auth import login, logout, get_user_model
from .tasks import send_password_reset_mail, change_email_success_mail
from .services import get_clean_email
from Order.models import Order, OrderItem

User = get_user_model()


class Registration(View):

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            form = UserRegistration()
            return render(self.request, 'Users/registration.html', {'form': form})
        else:
            return redirect('customer-account')

    def post(self, *args, **kwargs):
        form = UserRegistration(self.request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = get_clean_email(form.cleaned_data['email'])
            # get_clean_email returns email without all symbols after @
            user.save()

            try:
                login(self.request, user)
                messages.success(self.request, 'You successfully created an account!')
            except (Exception,):
                messages.error(self.request, 'Something went wrong. Try again.')

            self.request.user.username = f'user{self.request.user.id}'
            self.request.user.save()
            return redirect('all_products')
        return render(self.request, 'Users/registration.html', {'form': form})


class Authentication(View):

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            form = AuthenticationForm()
            return render(self.request, 'Users/authentication.html', {'form': form})
        else:
            return redirect(self.request.path)

    def post(self, *args, **kwargs):
        form = AuthenticationForm(data=self.request.POST)

        if form.is_valid():
            user = form.get_user()
            login(self.request, user)
            return redirect('customer-account')
        else:
            messages.error(self.request, 'Login or password is wrong')
        return render(self.request, 'Users/authentication.html', {'form': form})


class Logout(View):

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            try:
                logout(self.request)
                messages.success(self.request, 'You successfully logged out!')
            except (Exception,):
                messages.error(self.request, 'Something went wrong. Try again.')
        else:
            messages.error(self.request, 'You can\'t logout if you are not authenticated')
        return redirect('authentication')


class UserDetailPage(View):

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('registration')
        else:
            user = self.request.user
            context = {
                'user': user
            }
            return render(self.request, template_name='Users/account.html', context=context)


class UserResetPassword(View):

    def get(self, *args, **kwargs):
        reset_form = UserResetPasswordForm()
        return render(self.request, 'Users/password_reset_page.html', {'reset_form': reset_form})

    def post(self, *args, **kwargs):
        reset_form = UserResetPasswordForm(self.request.POST)

        if reset_form.is_valid():
            email = reset_form.cleaned_data['email']

            try:
                user = User.objects.get(email=email)

                if user:
                    subject = 'Requested password reset'
                    email_template_name = 'Users/password_reset_mail_template.html'
                    cont = {
                        'email': email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'OnlineShop',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    msg_html = render_to_string(email_template_name, cont)
                    send_password_reset_mail.delay(subject, email, msg_html)
                    messages.success(self.request, 'Mail was sent successfully!')
            except (Exception,):
                messages.error(self.request, 'User with this email does not exist!')

        return render(self.request, 'Users/password_reset_page.html', {'reset_form': reset_form})


class UserChangePassword(View):

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            user = self.request.user
            form = UserChangePasswordForm(user=user)
            return render(self.request, 'Users/password-change.html', {'form': form})
        else:
            return redirect('registration')

    def post(self, *args, **kwargs):
        user = self.request.user
        form = UserChangePasswordForm(data=self.request.POST, user=user)

        if form.is_valid():
            user.set_password(form.cleaned_data['new_password1'])
            user.save()
            messages.success(self.request, 'You successfully changed your password!')
        return render(self.request, 'Users/password-change.html', {'form': form})


class UserChangeEmailView(LoginRequiredMixin, View):
    login_url = 'registration'

    def get(self, *args, **kwargs):
        form = ChangeEmailForm()
        context = {
            'form': form
        }
        return render(self.request, template_name='Users/user-change-email.html', context=context)

    def post(self, *args, **kwargs):
        user = self.request.user
        form = ChangeEmailForm(self.request.POST)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.save()

            change_email_success_mail.delay(user.username, user.email)
            messages.success(self.request, 'Mail has been successfully changed, please, confirm it.')
        return render(self.request, 'Users/user-change-email.html', {'user': user, 'form': form})


class UserOrders(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'Users/user-orders.html'
    context_object_name = 'orders'
    login_url = 'registration'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, paid=True)


class UserOrderDetail(LoginRequiredMixin, View):
    login_url = 'registration'

    def get(self, *args, **kwargs):
        order = get_object_or_404(Order, id=kwargs['order_id'], paid=True)
        order_items = OrderItem.objects.filter(order=order).select_related('product__main_category',
                                                                           'product__subcategory')

        context = {
            'order': order,
            'order_items': order_items
        }
        return render(self.request, template_name='Users/user-order-detail.html', context=context)


class UserCoupons(LoginRequiredMixin, View):
    login_url = 'registration'

    def get(self, *args, **kwargs):
        coupons = Coupons.objects.filter(user=self.request.user)

        context = {
            'coupons': coupons
        }
        return render(self.request, template_name='Users/user-coupons.html', context=context)

OnlineShop/Users/templates/Users/account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tài khoản của tôi
{% endblock %}

{% block content %}


    <div class="card mb-3" style="width: 2000px;">
        <div class="row g-0">
            <div class="col-md-12">
                {% if user.photo %}
                    <img src="{{ user.photo.url }}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px">

                {% else %}
                    <img src="{% static 'icon/default-user-icon-8.png' %}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px;
                          border-radius: 12px">
                {% endif %}
                <h5 class="user-full-name" style="margin-left: 5px">{{ user.name }} {{ user.last_name }}</h5>
                <hr>


            </div>

            <div class="col-md-4">
                <div class="list-group list-group-flush" style="width: 80%">
                    <a href="#" class="list-group-item list-group-item-action">Kho voucher</a>
                    <a href="{% url 'user-orders' %}" class="list-group-item list-group-item-action">Đơn hàng của tôi</a>
                    <a href="#" class="list-group-item list-group-item-action">Yêu thích</a>
                    <a href="{% url 'customer-account' %}" class="list-group-item list-group-item-action active"
                       aria-current="true">Thông tin cá nhân</a>
                </div>
                <a href="{% url 'logout' %}">
                    <img src="{% static 'icon/61208.png' %}" alt=""
                         style="width: 30px; margin-right: 5px; margin-left: 250px">
                    Thoát
                </a>
            </div>

            <div class="col-md-8 personal-info">
                <h1 class="pers-info-title" style="margin-bottom: 50px">Thông tin cá nhân của tôi</h1>
                <div class="card-body">
                    <h3 class="card-title" style="margin-left: 100px">
                        Thông tin cá nhân
                    </h3>
                    {% if user.name or user.last_name or user.surname %}
                        <h6 class="card-text"
                            style="margin-left: 100px; margin-top: 40px">
                            Tên đầy đủ: {{ user.name }} {{ user.last_name }} {{ user.surname }}</h6>
                    {% endif %}

                    {% if user.phone %}
                        <h6 class="card-text"
                            style="margin-left: 100px; margin-top: 15px">Số điện thoại: {{ user.phone }}</h6>
                    {% endif %}

                    <h6 class="card-text"
                        style="margin-left: 100px; margin-top: 15px">Email: {{ user.email }}</h6>


                    <br>
                    <br>
                    <h3 class="card-title" style="margin-left: 100px">
                        Địa chỉ giao hàng
                    </h3>
                    {% if user.city %}
                        <h6 class="card-text"
                            style="margin-left: 100px; margin-top: 40px">
                            Địa chỉ: {{ user.city }}</h6>
                    {% endif %}
                    <h6 class="card-text"
                        style="margin-left: 100px; margin-top: 15px">Số điện thoại: {{ user.phone }}</h6>
                    <h6 class="card-text"
                        style="margin-left: 100px; margin-top: 15px">Email: {{ user.email }}</h6>


                </div>
            </div>
        </div>
    </div>



{% endblock %}

OnlineShop/Users/templates/Users/authentication.html
{% extends 'base.html' %}

{% block titlte %}
    Đăng nhập
{% endblock %}

{% block content %}
    <form action="" method="post" style="width: 35%">
        {% csrf_token %}
        <h1>Thông tin đăng nhập</h1>
        {{ form.non_field.errors }}
        <p>
            <label for="id_username">Email:</label>
            <input type="text" name="username" class="form-control" id="id_username">
            {{ form.username.errors }}
        </p>

        <p>
            <label for="id_password">Mật khẩu:</label>
            <input type="password" name="password" class="form-control" id="id_password">
            {{ form.password.errors }}
        </p>
        <button type="submit" class="btn btn-dark btn-block">Đăng nhập</button>

    </form>
{% endblock %}

OnlineShop/Users/templates/Users/user-order-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tài khoản của tôi
{% endblock %}

{% block content %}


    <div class="card mb-3" style="width: 2000px;">
        <div class="row g-0">
            <div class="col-md-12">
                {% if user.photo %}
                    <img src="{{ user.photo.url }}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px">

                {% else %}
                    <img src="{% static 'icon/default-user-icon-8.png' %}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px;
                          border-radius: 12px">
                {% endif %}
                <h5 class="user-full-name" style="margin-left: 5px">{{ user.name }} {{ user.last_name }}</h5>
                <hr>

            </div>

            <div class="col-md-4">
                <div class="list-group list-group-flush" style="width: 80%">
                    <a href="#" class="list-group-item list-group-item-action">Kho vouchers</a>
                    <a href="{% url 'user-orders' %}" class="list-group-item list-group-item-action active"
                       aria-current="true">Giỏ hàng của tôi</a>
                    <a href="#" class="list-group-item list-group-item-action">Yêu thích</a>
                    <a href="{% url 'customer-account' %}" class="list-group-item list-group-item-action">Thông tin cá nhân</a>
                </div>
                <a href="{% url 'logout' %}">
                    <img src="{% static 'icon/61208.png' %}" alt=""
                         style="width: 30px; margin-right: 5px; margin-left: 250px">
                    Đăng xuất
                </a>
            </div>

            <div class="col-md-8 personal-info">
                <h1 class="pers-info-title" style="margin-bottom: 50px">Đơn hàng: № {{ order.id }}</h1>
                <div class="card-body">

                    <div class="order" style="margin-left: 100px; margin-top: 40px">

                        <div class="card" style="border: 1px solid white !important">
                            <h5 class="card-header">№ {{ order.id }}</h5>
                            <div class="card-body">
                                <h5 class="card-title">{{ order.created|date:"d-m-Y" }}</h5>
                                {% if order.order_status is 1 %}
                                    <p class="card-text"
                                       style="color: green">{{ order.get_order_status_display }}</p>
                                {% else %}
                                    <p class="card-text"
                                       style="color: yellow">{{ order.get_order_status_display }}</p>
                                {% endif %}

                                <p class="card-text">
                                <h5>Order bonuses</h5>
                                <h6>{{ order.order_bonuses }} đ<small></small></h6>
                                </p>

                                <hr>

                                {% for item in order_items %}
                                    <div class="card">
                                        <div class="card-body">
                                            <a href="{{ item.product.get_absolute_url }}">
                                                <img src="{{ item.product.img.url }}" alt="" width="150">
                                            </a>
                                            <a href="{{ item.product.get_absolute_url }}"><h5
                                                    class="card-title">{{ item.product.name }}</h5></a>
                                            <p class="card-text"><h6>{{ item.quantity }} sản phẩm</h6></p>
                                            <p class="card-text"><h6>{{ item.product.get_price_view }} <small>đ</small>
                                        </div>
                                    </div>
                                {% endfor %}

                                <hr>

                                <div class="shipping">
                                    <h2>Shipping:</h2>
                                    <p class="card-text">Status: {{ order.get_order_status_display }}</p>
                                    <p class="card-text">
                                        Address: {{ order.country }}, {{ order.city }}, {{ order.address }}
                                    </p>
                                    <p class="card-text">Recipient: {{ order.last_name }} {{ order.name }}</p>
                                    <p class="card-text">Recipient number: {{ order.phone }}</p>
                                </div>

                                <hr>
                                <div class="total">
                                    <h2>Total:</h2>
                                    <p class="card-text"><h5>{{ order.get_order_total_price_view }}
                                    <small>đ</small>
                                </h5></p>

                                </div>


                            </div>
                        </div>

                    </div>


                    <br>
                    <br>


                </div>
            </div>
        </div>
    </div>


{% endblock %}

OnlineShop/Users/templates/Users/user-orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tài khoản của tôi
{% endblock %}

{% block content %}


    <div class="card mb-3" style="width: 2000px;">
        <div class="row g-0">
            <div class="col-md-12">
                {% if user.photo %}
                    <img src="{{ user.photo.url }}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px">

                {% else %}
                    <img src="{% static 'icon/default-user-icon-8.png' %}" class="img-fluid rounded-start" alt="..."
                         style="margin-left: 5px; margin-top: 20px; margin-bottom: 20px; width: 120px;
                          border-radius: 12px">
                {% endif %}
                <h5 class="user-full-name" style="margin-left: 5px">{{ user.name }} {{ user.last_name }}</h5>
                <hr>

            </div>

            <div class="col-md-4">
                <div class="list-group list-group-flush" style="width: 80%">

                    <a href="#" class="list-group-item list-group-item-action">Coupons</a>
                    <a href="{% url 'user-orders' %}" class="list-group-item list-group-item-action active"
                       aria-current="true">Đơn hàng của tôi</a>
                    <a href="#" class="list-group-item list-group-item-action">Yêu thích</a>
                    <a href="{% url 'customer-account' %}" class="list-group-item list-group-item-action">Thông tin cá nhân</a>
                </div>
                <a href="{% url 'logout' %}">
                    <img src="{% static 'icon/61208.png' %}" alt=""
                         style="width: 30px; margin-right: 5px; margin-left: 250px">
                    Thoát
                </a>
            </div>

            <div class="col-md-8 personal-info">
                <h1 class="pers-info-title" style="margin-bottom: 50px">Đơn hàng của tôi</h1>
                <div class="card-body">
                    <h3 class="card-title" style="margin-left: 100px">
                        Đơn hàng
                    </h3>

                    <div class="orders" style="margin-left: 100px; margin-top: 40px">
                        {% if orders %}
                            {% for order in orders %}
                                <div class="card" style="border: 1px solid white !important">
                                    <h5 class="card-header">№ {{ order.id }}</h5>
                                    <div class="card-body">
                                        <h5 class="card-title">{{ order.created|date:"d-m-Y" }}</h5>
                                        {% if order.order_status is 1 %}
                                            <p class="card-text"
                                               style="color: green">{{ order.get_order_status_display }}</p>
                                        {% else %}
                                            <p class="card-text"
                                               style="color: yellow">{{ order.get_order_status_display }}</p>
                                        {% endif %}
                                        <p class="card-text"><h6>{{ order.get_order_total_price_view }}
                                        <small>đ</small>
                                    </h6></p>

                                        <a href="{% url 'user-order-detail' order.id %}" class="btn btn-dark">Thêm thông tin</a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <h6>Bạn hiện không có đơn hàng nào</h6>
                        {% endif %}

                    </div>


                    <br>
                    <br>


                </div>
            </div>
        </div>
    </div>



{% endblock %}